# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: This be Vito's site.
email: vito@compcorrect.cc
description: > # this means to ignore newlines until "baseurl:"
  Nick is no good.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.vitoreiter.com" # the base hostname & protocol for your site
instagram: v_reiter

# Build settings
markdown: kramdown
